add verify step

diff --git a/.github/workflows/azure-static-web-apps-purple-meadow-096ad960f.yml b/.github/workflows/azure-static-web-apps-purple-meadow-096ad960f.yml
--- a/.github/workflows/azure-static-web-apps-purple-meadow-096ad960f.yml
+++ b/.github/workflows/azure-static-web-apps-purple-meadow-096ad960f.yml
@@ -27,6 +27,14 @@ jobs:
           npm install --force
           npm run build
 
+      - name: Verify index.html exists
+        run: |
+          if [ ! -f build/frontend/index.html ]; then
+            echo "index.html not found!"
+            exit 1
+          fi
+          echo "index.html found."
+
       - name: Build And Deploy
         uses: Azure/static-web-apps-deploy@v1
         with:
